version: '3'
services:
    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile.dev
        ports:
            - 80:80
        restart: always
        depends_on:
            - frontend
            - backend
    frontend:
        stdin_open: true
        container_name: frontend
        build:
            context: ./../react-redux-starter
            dockerfile: Dockerfile.dev
        volumes:
            - /usr/app/node_modules
            - ../react-redux-starter:/usr/app
    backend:
        container_name: backend
        build:
            context: ./../node-starter
            dockerfile: Dockerfile.dev
        environment:
            - MONGODB_URI_LOCAL=mongodb://node:password@database:27017/node-starter
            - PORT=5000
        volumes:
            - /usr/app/node_modules
            - ../node-starter:/usr/app
        links:  #depends_on
            - database
    database:
        container_name: mongo-container
        build:
            context: ./mongo
            dockerfile: Dockerfile
        restart: always
        command: ["--bind_ip_all"]
        volumes:
            - ./mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro  # ro means read-only
            - ./mongo/mongo-volume:/data/db
        ports:
            - "27017-27019:27017-27019"